apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: k8s-web-application
build:
  artifacts:
    # - image: taskit
    - image: gitlab.lnu.se:5050/2dv013/student/am224wd/part2-architecture/kuberneterized-web-application/taskit # Updated to my project url
      docker:
        dockerfile: Dockerfile.development ##### DON'T FORGET TO CHANGE THIS TO Dockerfile.production
manifests:
  rawYaml:
    - k8s/ingress.yaml
    - k8s/mongodb.yaml
    - k8s/taskit.yaml
    - k8s/redis.yaml
deploy:
  kubectl: {}

# Production profile
# A slightly modyfied ingress configuration needed in production.
profiles:
- name: production
  patches:
  - op: replace 
    path: /manifests/rawYaml/0  # JSON Pointer to ingress.yaml
    value: k8s/ingress.production.yaml  # The value for the ingressClassName field is added in this one