# notifications.yaml

apiVersion: v1
kind: Service
metadata:
  name: notifications
spec:
  ports:
    - name: "notif-port"
      port: 3001
      targetPort: notif-http
  selector:
    app: notifications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  replicas: 2  # Multiple instances 
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: gitlab.lnu.se:5050/2dv013/student/am224wd/part2-architecture/kuberneterized-web-application/taskit
          # command: ["npm", "run", "start-notification-service"]
          env:
            - name: DB_CONNECTION_STRING
              value: "mongodb://mongodb:27017/tasks"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: QUEUE_URL
              value: "amqp://user:password@rabbitmq.default.svc.cluster.local:5672/"
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-bot-token    # Name of the Secret 
                  key: SLACK_BOT_TOKEN     # Key within the Secret
          ports:
            - containerPort: 3001
              name: notif-http
      imagePullSecrets:
        - name: regcred
