apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: amqp
      port: 5672      # AMQP port
      targetPort: 5672
    - name: management
      port: 15672     # Management UI port
      targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - containerPort: 5672    # AMQP port
          - containerPort: 15672   # Management UI port
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: "user"          # Default username
          - name: RABBITMQ_DEFAULT_PASS
            value: "password"      # Default password